let games = [
    {'id': 0, 'text': 'NOVEMBER', 'notable': false},
    {'id': 1, 'text': '----------------', 'notable': false},
    {'id': 2, 'text': 'Farmagia', 'notable': false},
    {'id': 3, 'text': 'Homichiper', 'notable': false},
    {'id': 4, 'text': 'RATSHAKER', 'notable': false},
    {'id': 5, 'text': 'Blackthorn Arena: Reforged', 'notable': false},
    {'id': 6, 'text': 'DEATH NOTE Killer Witin', 'notable': false},
    {'id': 7, 'text': 'Metal Slug Tactics', 'notable': false},
    {'id': 8, 'text': 'Planet Coaster 2', 'notable': false},
    {'id': 9, 'text': 'Surviving the Abyss', 'notable': false},
    {'id': 10, 'text': 'Taiko no Tatsujin: Rhythm Festival', 'notable': false},
    {'id': 11, 'text': 'Teenage Mutant Ninja Turtles: Splintered Fate', 'notable': false},
    {'id': 12, 'text': 'Death of the Reprobate', 'notable': false},
    {'id': 13, 'text': 'Goat Simluator: Remastered', 'notable': false},
    {'id': 14, 'text': 'Mario and Luigi: Brothership', 'notable': false},
    {'id': 15, 'text': 'Sengoku Dynasty', 'notable': false},
    {'id': 16, 'text': 'Metro Awakening', 'notable': false},
    {'id': 17, 'text': 'Empire of the Ants', 'notable': false},
    {'id': 18, 'text': 'PROXIMATE', 'notable': false},
    {'id': 19, 'text': 'ZEPHON', 'notable': false},
    {'id': 20, 'text': 'NO STRANGERS', 'notable': false},
    {'id': 21, 'text': 'Slitterhead', 'notable': false},
    {'id': 22, 'text': 'Select Oblige', 'notable': false},
    {'id': 23, 'text': 'Take me, Vitaly', 'notable': false},
    {'id': 24, 'text': 'Dungeons of Blood and Dream', 'notable': false},
    {'id': 25, 'text': 'Menace from the Deep', 'notable': false},
    {'id': 26, 'text': 'Shape of Dreams: Prolouge', 'notable': false},
    {'id': 27, 'text': 'XENOTILT: HOSTILE PINBALL ACTION', 'notable': false},
    {'id': 28, 'text': 'The Rise of the Golden Idle', 'notable': false},
    {'id': 29, 'text': 'Farming Simulator 25', 'notable': false},
    {'id': 30, 'text': 'In Sink: A Co-op Escape Adventure', 'notable': false},
    {'id': 31, 'text': 'Is this Game Trying to Kill Me?', 'notable': false},
    {'id': 32, 'text': 'Mind over Matter', 'notable': false},
    {'id': 33, 'text': 'I Am Fury: Cozy Apocalypse Survival', 'notable': false},
    {'id': 34, 'text': 'Song of Silence', 'notable': false},
    {'id': 35, 'text': '420BLAZEIT 2: GAME OF THE YEAR -=Dank Dreams and Goated Memes=- [#wow/11 Like and Subscribe] Poggerz Edition', 'notable': false},
    {'id': 36, 'text': 'Sorry We\'re Closed', 'notable': false},
    {'id': 37, 'text': 'Little Big Adventure - Twinsen\'s Quest', 'notable': false},
    {'id': 38, 'text': 'Space Trash Scavenger', 'notable': false},
    {'id': 39, 'text': 'DRAGON QUEST III HD-2D Remake', 'notable': false},
    {'id': 40, 'text': 'Deathless Death', 'notable': false},
    {'id': 41, 'text': 'LEGO® Horizon Adventures', 'notable': false},
    {'id': 42, 'text': 'Great God Grove', 'notable': false},
    {'id': 43, 'text': 'Deep Space Cache', 'notable': false},
    {'id': 44, 'text': 'Bioweaver', 'notable': false},
    {'id': 45, 'text': 'Ice World', 'notable': false},
    {'id': 46, 'text': 'Maid Cafe on Electric Street', 'notable': false},
    {'id': 47, 'text': 'Seer\'s Gambit', 'notable': false},
    {'id': 48, 'text': 'Incantation', 'notable': false},
    {'id': 49, 'text': 'THRESHOLD', 'notable': false},
    {'id': 50, 'text': 'Microsoft Flight Simulator 2024', 'notable': false},
    {'id': 51, 'text': 'Luma Island', 'notable': false},
    {'id': 52, 'text': 'S.T.A.L.K.E.R. 2: Heart of Chornobyl', 'notable': false},
    {'id': 53, 'text': 'Loco Motive', 'notable': false},
    {'id': 54, 'text': 'ICBM: Escalation', 'notable': false},
    {'id': 55, 'text': 'The Devil Within: Satgat', 'notable': false},
    {'id': 56, 'text': 'Strinova', 'notable': false},
    {'id': 57, 'text': 'Alaloth: Champions of The Four Kingdoms', 'notable': false},
    {'id': 58, 'text': 'Follow the meaning', 'notable': false},
    {'id': 59, 'text': 'Mercury Abbey', 'notable': false},
    {'id': 60, 'text': 'Fantasy Aquarium', 'notable': false},
    {'id': 61, 'text': 'Void Crew', 'notable': false},
    {'id': 62, 'text': 'Lost But Found', 'notable': false},
    {'id': 63, 'text': 'Mindlock - The Apartment', 'notable': false},
    {'id': 64, 'text': 'Enigma of Fear', 'notable': false},
    {'id': 65, 'text': 'HOLE', 'notable': false},
    {'id': 66, 'text': '', 'notable': false},
    {'id': 67, 'text': 'DECEMBER', 'notable': false},
    {'id': 68, 'text': '------------------', 'notable': false},
    {'id': 69, 'text': 'Get To Work', 'notable': false},
    {'id': 70, 'text': 'ANTONBLAST', 'notable': false},
    {'id': 71, 'text': 'Pavlov', 'notable': false},
    {'id': 72, 'text': 'Battle Shapers', 'notable': false},
    {'id': 73, 'text': 'Delta Force', 'notable': false},
    {'id': 74, 'text': 'Fantasian Neo Dimension', 'notable': false},
    {'id': 75, 'text': 'Caves of Qud', 'notable': false},
    {'id': 76, 'text': 'Priest Simulator: Vampire Show', 'notable': false},
    {'id': 77, 'text': 'The Thing: Remastered', 'notable': false},
    {'id': 78, 'text': 'Uncle Chop\'s Rocket Shop', 'notable': false},
    {'id': 79, 'text': '[Bober Bros] The Hole', 'notable': false},
    {'id': 80, 'text': 'Deadside', 'notable': false},
    {'id': 81, 'text': 'Railroads Online', 'notable': false},
    {'id': 82, 'text': 'Skydance\'s BEHEMOTH', 'notable': false},
    {'id': 83, 'text': 'Granny: Escape Together', 'notable': false},
    {'id': 84, 'text': 'Marvel Rivals', 'notable': false},
    {'id': 85, 'text': 'UNLIGHT:Revive', 'notable': false},
    {'id': 86, 'text': 'Digseum', 'notable': false},
    {'id': 87, 'text': 'A Shelter Full of Cats', 'notable': false},
    {'id': 88, 'text': 'Indiana Jones and the Great Circle', 'notable': false},
    {'id': 89, 'text': 'DigDigDrill', 'notable': false},
    {'id': 90, 'text': 'Legacy of Kain Soul Reaver 1&2 Remastered', 'notable': false},
    {'id': 91, 'text': 'Ballionaire', 'notable': false},
    {'id': 92, 'text': 'Mighty Morphin Power Rangers: Rita\'s Rewind', 'notable': false},
    {'id': 93, 'text': 'MiSide', 'notable': false},
    {'id': 94, 'text': 'ADEN', 'notable': false},
    {'id': 95, 'text': 'Hatsuyuki Sakura', 'notable': false},
    {'id': 96, 'text': 'Clone Drone in the Hyperdome', 'notable': false},
    {'id': 97, 'text': 'There Exists Nobody', 'notable': false},
    {'id': 98, 'text': 'Murky Divers', 'notable': false},
    {'id': 99, 'text': 'Deathless. The Hero Quest', 'notable': false},
    {'id': 100, 'text': 'IRON REBELLION', 'notable': false},
    {'id': 101, 'text': 'Creeper World IXE', 'notable': false},
    {'id': 102, 'text': 'The Cabin Factory', 'notable': false},
    {'id': 103, 'text': 'SimRail - The Railway Simulator', 'notable': false},
    {'id': 104, 'text': 'Awaria', 'notable': false},
    {'id': 105, 'text': 'The NOexistenceN of you AND me', 'notable': false},
    {'id': 106, 'text': 'Rocket Rats', 'notable': false},
    {'id': 107, 'text': 'ENSCROLL', 'notable': false},
    {'id': 108, 'text': 'Office Life', 'notable': false},
    {'id': 109, 'text': 'Taiwan Love Story⁵', 'notable': false},
    {'id': 110, 'text': 'Grimlord', 'notable': false},
    {'id': 111, 'text': 'Alien: Rogue Incursion VR', 'notable': false},
    {'id': 112, 'text': 'Talented', 'notable': false},
    {'id': 113, 'text': 'Banebush', 'notable': false},
    {'id': 114, 'text': 'Winion Virus', 'notable': false},
    {'id': 115, 'text': 'The Burton Equation', 'notable': false},
    {'id': 116, 'text': 'Sixtar Gate: STARTRAIL', 'notable': false},
    {'id': 117, 'text': '', 'notable': false},
    {'id': 118, 'text': 'JANUARY', 'notable': false},
    {'id': 119, 'text': '------------------', 'notable': false},
    {'id': 120, 'text': 'On your Tail', 'notable': false},
    {'id': 121, 'text': 'Beyond Citadel', 'notable': false},
    {'id': 122, 'text': 'Amenti', 'notable': false},
    {'id': 123, 'text': 'Click Mage', 'notable': false},
    {'id': 124, 'text': 'Sea Fantasy', 'notable': false},
    {'id': 125, 'text': 'CRUEL', 'notable': false},
    {'id': 126, 'text': 'S4U: CITYPUNK 2011 AND LOVE PUNCH', 'notable': false},
    {'id': 127, 'text': 'The Rangers In The South', 'notable': false},
    {'id': 128, 'text': 'FREEDOM WARS Remastered', 'notable': false},
    {'id': 129, 'text': 'The Inn-Sanity', 'notable': false},
    {'id': 130, 'text': 'Cursed Digicam | 呪われたデジカメ', 'notable': false},
    {'id': 131, 'text': 'Threefold Recital', 'notable': false},
    {'id': 132, 'text': 'Heroes of Hammerwatch II', 'notable': false},
    {'id': 133, 'text': 'The Roottrees are Dead', 'notable': false},
    {'id': 134, 'text': 'Game of Fate 2: A Century\'s Promise', 'notable': false},
    {'id': 135, 'text': 'Age of Darkness: Final Stand', 'notable': false},
    {'id': 136, 'text': 'Football Coach: College Dynasty', 'notable': false},
    {'id': 137, 'text': 'BLADECHIMERA', 'notable': false},
    {'id': 138, 'text': 'Tyrant\'s Realm', 'notable': false},
    {'id': 139, 'text': 'Age of Water', 'notable': false},
    {'id': 140, 'text': 'DYNASTY WARRIORS: ORIGINS', 'notable': false},
    {'id': 141, 'text': 'Last Train Outta\' Wormtown', 'notable': false},
    {'id': 142, 'text': 'Nunholy', 'notable': false},
    {'id': 143, 'text': 'SKIBIDI GYATROOMS', 'notable': false},
    {'id': 144, 'text': 'IDUN - Frontline Survival', 'notable': false},
    {'id': 145, 'text': 'NEEDY STREAMER OVERLOAD: Typing of The Net', 'notable': false},
    {'id': 146, 'text': 'Cyber Manhunt 2: New World - The Hacking Simulator', 'notable': false},
    {'id': 147, 'text': 'Lonely Mountains: Snow Riders', 'notable': false},
    {'id': 148, 'text': 'Matchmaking Inc.', 'notable': false},
    {'id': 149, 'text': 'None Shall Intrude', 'notable': false},
    {'id': 150, 'text': 'ENDER MAGNOLIA: Bloom in the Mist', 'notable': false},
    {'id': 151, 'text': 'Mika and The Witch\'s Mountain', 'notable': false},
    {'id': 152, 'text': 'Butcher\'s Creek', 'notable': false},
    {'id': 153, 'text': 'Dreamcore', 'notable': false},
    {'id': 154, 'text': 'NINJA GAIDEN 2 Black', 'notable': false},
    {'id': 155, 'text': 'SYNDUALITY Echo of Ada', 'notable': false},
    {'id': 156, 'text': 'Rock Star Life Simulator', 'notable': false},
    {'id': 157, 'text': 'Jaded', 'notable': false},
    {'id': 158, 'text': 'Those Who Rule', 'notable': false},
    {'id': 159, 'text': 'Virtua Fighter 5 R.E.V.O. World Stage', 'notable': false},
    {'id': 160, 'text': 'Camping Simulator: The Squad', 'notable': false},
    {'id': 161, 'text': 'Eternal Strands', 'notable': false},
    {'id': 162, 'text': 'Tails of Iron 2: Whiskers of Winter', 'notable': false},
    {'id': 163, 'text': 'Exogate Initiative', 'notable': false},
    {'id': 164, 'text': 'Orcs Must Die! Deathtrap', 'notable': false},
    {'id': 165, 'text': 'Kiosk', 'notable': false},
    {'id': 166, 'text': 'DEAD LETTER DEPT.', 'notable': false},
    {'id': 167, 'text': 'Hello Kitty Island Adventure', 'notable': false},
    {'id': 168, 'text': 'The Headliners', 'notable': false},
    {'id': 169, 'text': 'Sniper Elite: Resistance', 'notable': false},
    {'id': 170, 'text': 'FlyKnight', 'notable': false},
    {'id': 171, 'text': 'Citizen Sleeper 2: Starward Vector', 'notable': false},
    {'id': 172, 'text': 'My Little Life', 'notable': false},
    {'id': 173, 'text': 'Double Shoulders', 'notable': false},
    {'id': 174, 'text': '', 'notable': false},
    {'id': 175, 'text': 'FEBRUARY', 'notable': false},
    {'id': 176, 'text': '---------------------', 'notable': false},
    {'id': 177, 'text': 'Rift Wizard 2', 'notable': false},
    {'id': 178, 'text': 'Kingdom Come: Deliverance II', 'notable': false},
    {'id': 179, 'text': 'Blood Bar Tycoon', 'notable': false},
    {'id': 180, 'text': 'Rift of the NecroDancer', 'notable': false},
    {'id': 181, 'text': 'UNDERWARD', 'notable': false},
    {'id': 182, 'text': 'of the Devil', 'notable': false},
    {'id': 183, 'text': 'Keep Driving', 'notable': false},
    {'id': 184, 'text': 'Border Pioneer', 'notable': false},
    {'id': 185, 'text': 'Big Helmet Heroes', 'notable': false},
    {'id': 186, 'text': 'Stray Path', 'notable': false},
    {'id': 187, 'text': 'Ambulance Life: A Paramedic Simulator', 'notable': false},
    {'id': 188, 'text': 'Grapples Galore', 'notable': false},
    {'id': 189, 'text': 'A Game About Digging A Hole', 'notable': false},
    {'id': 190, 'text': 'Grandpa High on Retro', 'notable': false},
    {'id': 191, 'text': 'Reality Break', 'notable': false},
    {'id': 192, 'text': 'Project Hailstorm', 'notable': false},
    {'id': 193, 'text': 'Sid Meier\'s Civilization VII', 'notable': false},
    {'id': 194, 'text': 'The Executive - Movie Industry Tycoon', 'notable': false},
    {'id': 195, 'text': 'GIRLS\' FRONTLINE 2: EXILIUM', 'notable': false},
    {'id': 196, 'text': 'Urban Myth Dissolution Center', 'notable': false},
    {'id': 197, 'text': 'Mind Over Magic', 'notable': false},
    {'id': 198, 'text': 'WARRIORS: Abyss', 'notable': false},
    {'id': 199, 'text': 'Guns of Fury', 'notable': false},
    {'id': 200, 'text': 'Panelka', 'notable': false},
    {'id': 201, 'text': 'Rugby 25', 'notable': false},
    {'id': 202, 'text': 'Tomb Raider IV-VI Remastered', 'notable': false},
    {'id': 203, 'text': 'Flash Doll', 'notable': false},
    {'id': 204, 'text': 'NO-SKIN', 'notable': false},
    {'id': 205, 'text': 'SNØ: Ultimate Freeriding', 'notable': false},
    {'id': 206, 'text': 'Tiny Pasture', 'notable': false},
    {'id': 207, 'text': 'Lost Records: Bloom & Rage', 'notable': false},
    {'id': 208, 'text': 'Microtopia', 'notable': false},
    {'id': 209, 'text': 'Avowed', 'notable': false},
    {'id': 210, 'text': 'Stories from Sol: The Gun-Dog', 'notable': false},
    {'id': 211, 'text': 'TRIBE NINE', 'notable': false},
    {'id': 212, 'text': 'Cabernet', 'notable': false},
    {'id': 213, 'text': 'Blood Typers', 'notable': false},
    {'id': 214, 'text': 'Like a Dragon: Pirate Yakuza in Hawaii', 'notable': false},
    {'id': 215, 'text': 'Whisker Squadron: Survivor', 'notable': false},
    {'id': 216, 'text': 'Longvinter', 'notable': false},
    {'id': 217, 'text': 'Stellar Settlers: Space Base Builder', 'notable': false},
    {'id': 218, 'text': 'The Test: Reality Check', 'notable': false},
    {'id': 219, 'text': 'FACEMINER', 'notable': false},
    {'id': 220, 'text': 'PGA TOUR 2K25', 'notable': false},
    {'id': 221, 'text': 'Monster Hunter Wilds', 'notable': false},
    {'id': 222, 'text': '', 'notable': false},
    {'id': 223, 'text': 'MARCH', 'notable': false},
    {'id': 224, 'text': '----------------', 'notable': false},
    {'id': 225, 'text': 'Two Point Museum', 'notable': false},
    {'id': 226, 'text': 'HENPRI', 'notable': false},
    {'id': 227, 'text': 'Everhood 2', 'notable': false},
    {'id': 228, 'text': 'Knights in Tight Spaces', 'notable': false},
    {'id': 229, 'text': 'War Robots: Frontiers', 'notable': false},
    {'id': 230, 'text': 'Bongo Cat', 'notable': false},
    {'id': 231, 'text': 'Split Fiction', 'notable': false},
    {'id': 232, 'text': 'Suikoden I&II HD Remaster Gate Rune and Dunan Unification Wars', 'notable': false},
    {'id': 233, 'text': 'FragPunk', 'notable': false},
    {'id': 234, 'text': 'Do No Harm', 'notable': false},
    {'id': 235, 'text': 'One Lonely Outpost', 'notable': false},
    {'id': 236, 'text': 'Wizardry Variants Daphne', 'notable': false},
    {'id': 237, 'text': 'SERAPH : In the Darkness', 'notable': false},
    {'id': 238, 'text': 'Nubby\'s Number Factory', 'notable': false},
    {'id': 239, 'text': 'The Children of Clay', 'notable': false},
    {'id': 240, 'text': 'Saihate Station', 'notable': false},
    {'id': 241, 'text': 'Zombieville USA 3D', 'notable': false},
    {'id': 242, 'text': 'Rogue: Genesia', 'notable': false},
    {'id': 243, 'text': 'I Am Legion: Stand Survivors', 'notable': false},
    {'id': 244, 'text': 'Myrmidon', 'notable': false},
    {'id': 245, 'text': 'ORDER 13', 'notable': false},
    {'id': 246, 'text': 'Cheaters Cheetah', 'notable': false},
    {'id': 247, 'text': 'Wanderstop', 'notable': false},
    {'id': 248, 'text': 'That\'s not my Neighbor', 'notable': false},
    {'id': 249, 'text': 'ANEURISM IV', 'notable': false},
    {'id': 250, 'text': 'Metal Bringer', 'notable': false},
    {'id': 251, 'text': 'FATE: Reawakened', 'notable': false},
    {'id': 252, 'text': 'WWE 2K25', 'notable': false},
    {'id': 253, 'text': 'OUTLAWED', 'notable': false},
    {'id': 254, 'text': 'Out of the Park Baseball 26', 'notable': false},
    {'id': 255, 'text': 'ROGUE LIGHT DECK BUILDER', 'notable': false},
    {'id': 256, 'text': 'Pathologic 3: Quarantine', 'notable': false},
    {'id': 257, 'text': 'Party Club', 'notable': false},
    {'id': 258, 'text': 'MLB The Show 25', 'notable': false},
    {'id': 259, 'text': 'Mudborne: Frog Management Sim', 'notable': false},
    {'id': 260, 'text': 'Cataclismo', 'notable': false},
    {'id': 261, 'text': 'Assassin’s Creed Shadows', 'notable': false},
    {'id': 262, 'text': 'BLEACH Rebirth of Souls', 'notable': false},
    {'id': 263, 'text': 'Look Outside', 'notable': false},
    {'id': 264, 'text': 'Metal Garden', 'notable': false},
    {'id': 265, 'text': 'Urban Jungle', 'notable': false},
    {'id': 266, 'text': 'KAISERPUNK', 'notable': false},
    {'id': 267, 'text': 'Atelier Yumia: The Alchemist of Memories & the Envisioned Land', 'notable': false},
    {'id': 268, 'text': 'Dark Deity 2', 'notable': false},
    {'id': 269, 'text': 'Nordhold', 'notable': false},
    {'id': 270, 'text': 'Level Devil', 'notable': false},
    {'id': 271, 'text': 'Spilled!', 'notable': false},
    {'id': 272, 'text': 'Trials of Innocence', 'notable': false},
    {'id': 273, 'text': 'Guidus Zero', 'notable': false},
    {'id': 274, 'text': 'ENA: Dream BBQ', 'notable': false},
    {'id': 275, 'text': 'Shooters, Ready!', 'notable': false},
    {'id': 276, 'text': 'AI LIMIT', 'notable': false},
    {'id': 277, 'text': 'LIZARDS MUST DIE 2', 'notable': false},
    {'id': 278, 'text': 'KARMA: The Dark World', 'notable': false},
    {'id': 279, 'text': 'The First Berserker: Khazan', 'notable': false},
    {'id': 280, 'text': 'Atomfall', 'notable': false},
    {'id': 281, 'text': 'Gal Guardians: Servants of the Dark', 'notable': false},
    {'id': 282, 'text': 'ASURAJANG', 'notable': false},
    {'id': 283, 'text': 'Ambidextro', 'notable': false},
    {'id': 284, 'text': 'Squirreled Away', 'notable': false},
    {'id': 285, 'text': 'Emissary Zero', 'notable': false},
    {'id': 286, 'text': 'Sultan\'s Game', 'notable': false},
    {'id': 287, 'text': 'The Chef\'s Shift', 'notable': false},
    {'id': 288, 'text': '', 'notable': false},
    {'id': 289, 'text': 'APRIL', 'notable': false},
    {'id': 290, 'text': '------', 'notable': false},
    {'id': 291, 'text': 'Dreams of Aether', 'notable': false},
    {'id': 292, 'text': 'Haste', 'notable': false},
    {'id': 293, 'text': 'Hometopia', 'notable': false},
    {'id': 294, 'text': 'LONESTAR', 'notable': false},
    {'id': 295, 'text': 'Three Kingdoms: The Blood Moon', 'notable': false},
    {'id': 296, 'text': 'Gnomes', 'notable': false},
    {'id': 297, 'text': 'TETRIS® THE GRAND MASTER 4 -ABSOLUTE EYE-', 'notable': false},
    {'id': 298, 'text': 'Commander Quest', 'notable': false},
    {'id': 299, 'text': 'Nomad Idle', 'notable': false},
    {'id': 300, 'text': 'PEPPERED: an existential platformer', 'notable': false},
    {'id': 301, 'text': 'Lyca', 'notable': false},
    {'id': 302, 'text': 'Kādomon: Hyper Auto Battlers', 'notable': false},
    {'id': 303, 'text': 'South of Midnight', 'notable': false},
    {'id': 304, 'text': 'Burden of Command', 'notable': false},
    {'id': 305, 'text': 'GIRLS MADE PUDDING', 'notable': false},
    {'id': 306, 'text': 'PARANOIA PLACE', 'notable': false},
    {'id': 307, 'text': 'Commandos: Origins', 'notable': false},
    {'id': 308, 'text': 'Promise Mascot Agency', 'notable': false},
    {'id': 309, 'text': 'The Talos Principle: Reawakened', 'notable': false},
    {'id': 310, 'text': 'Blue Prince', 'notable': false},
    {'id': 311, 'text': 'Crashlands 2', 'notable': false},
    {'id': 312, 'text': 'Castle Of Alchemists', 'notable': false},
    {'id': 313, 'text': 'Lunacid - Tears of the Moon', 'notable': false},
    {'id': 314, 'text': 'Viscerafest', 'notable': false},
    {'id': 315, 'text': 'Forever Skies', 'notable': false},
    {'id': 316, 'text': 'Warside', 'notable': false},
    {'id': 317, 'text': 'Synergy', 'notable': false},
    {'id': 318, 'text': '#DRIVE Rally', 'notable': false},
    {'id': 319, 'text': 'Bionic Bay', 'notable': false},
    {'id': 320, 'text': 'Yao-Guai Hunter', 'notable': false},
    {'id': 321, 'text': 'Mandragora: Whispers of the Witch Tree', 'notable': false},
    {'id': 322, 'text': 'Pax Augusta', 'notable': false},
    {'id': 323, 'text': 'Soulslinger: Envoy of Death', 'notable': false},
    {'id': 324, 'text': 'Dysterra', 'notable': false},
    {'id': 325, 'text': 'Sunset Motel', 'notable': false},
    {'id': 326, 'text': 'Love Curse: Find Your Soulmate', 'notable': false},
    {'id': 327, 'text': 'Lumberjacked', 'notable': false},
    {'id': 328, 'text': 'Cornerpond', 'notable': false},
    {'id': 329, 'text': 'Out Of Hands', 'notable': false},
    {'id': 330, 'text': 'Havendock', 'notable': false},
    {'id': 331, 'text': 'The Elder Scrolls IV: Oblivion Remastered', 'notable': false},
    {'id': 332, 'text': 'Post Trauma', 'notable': false},
    {'id': 333, 'text': 'Dinkum', 'notable': false},
    {'id': 334, 'text': 'Old Skies', 'notable': false},
    {'id': 335, 'text': 'Sunderfolk', 'notable': false},
    {'id': 336, 'text': 'Beholder: Conductor', 'notable': false},
    {'id': 337, 'text': 'Dolls Nest', 'notable': false},
    {'id': 338, 'text': 'Clair Obscur: Expedition 33', 'notable': false},
    {'id': 339, 'text': 'Monster Prom 4: Monster Con', 'notable': false},
    {'id': 340, 'text': 'The Hundred Line -Last Defense Academy-', 'notable': false},
    {'id': 341, 'text': 'Tempest Rising', 'notable': false},
    {'id': 342, 'text': 'SpellRogue', 'notable': false},
    {'id': 343, 'text': 'FATAL FURY: City of the Wolves', 'notable': false},
    {'id': 344, 'text': 'BOKURA: planet', 'notable': false},
    {'id': 345, 'text': 'DARKEST DAYS', 'notable': false},
    {'id': 346, 'text': 'Necrophosis', 'notable': false},
    {'id': 347, 'text': 'Survivalist: Invisible Strain', 'notable': false},
    {'id': 348, 'text': 'World of Goo 2', 'notable': false},
    {'id': 349, 'text': 'Badlands Crew - Drive, Command, Conquer', 'notable': false},
    {'id': 350, 'text': 'Infinity Nikki', 'notable': false},
    {'id': 351, 'text': 'Approaching Infinity', 'notable': false},
    {'id': 352, 'text': 'Wizordum', 'notable': false},
    {'id': 353, 'text': 'SubwaySim 2', 'notable': false},
    {'id': 354, 'text': 'Age of Reforging:The Freelands', 'notable': false},
    {'id': 355, 'text': 'Path of Kung Fu', 'notable': false},
    {'id': 356, 'text': 'StarVaders', 'notable': false},
    {'id': 357, 'text': 'Skin Deep', 'notable': false},
    {'id': 358, 'text': 'KIBORG', 'notable': false},
    {'id': 359, 'text': 'MotoGP25', 'notable': false},
    {'id': 360, 'text': '', 'notable': false},
    {'id': 361, 'text': 'MAY', 'notable': false},
    {'id': 362, 'text': '------------', 'notable': false},
    {'id': 363, 'text': 'Ratopia', 'notable': false},
    {'id': 364, 'text': 'To Pixelia', 'notable': false},
    {'id': 365, 'text': 'Ocean Keeper: Dome Survival', 'notable': false},
    {'id': 366, 'text': 'A Night Filled With the Sound of Rain', 'notable': false},
    {'id': 367, 'text': 'Drop Duchy', 'notable': false},
    {'id': 368, 'text': 'Mini Settlers', 'notable': false},
    {'id': 369, 'text': 'Among Us 3D', 'notable': false},
    {'id': 370, 'text': 'Builders of Greece', 'notable': false},
    {'id': 371, 'text': 'Deck of Haunts', 'notable': false},
    {'id': 372, 'text': 'iDigging', 'notable': false},
    {'id': 373, 'text': 'The Midnight Walk', 'notable': false},
    {'id': 374, 'text': 'Cash Cleaner Simulator', 'notable': false},
    {'id': 375, 'text': 'Tower Dominion', 'notable': false},
    {'id': 376, 'text': 'Revenge of the Savage Planet', 'notable': false},
    {'id': 377, 'text': 'Spirit of the North 2', 'notable': false},
    {'id': 378, 'text': 'Yes, Your Grace 2: Snowfall', 'notable': false},
    {'id': 379, 'text': 'Tank Squad', 'notable': false},
    {'id': 380, 'text': 'Rhythm Witch: Beat Death', 'notable': false},
    {'id': 381, 'text': 'Ultimate Fishing® Simulator 2', 'notable': false},
    {'id': 382, 'text': 'Jacksmith: Weapons and Warriors', 'notable': false},
    {'id': 383, 'text': 'Labyrinth Of The Demon King', 'notable': false},
    {'id': 384, 'text': 'The Precinct', 'notable': false},
    {'id': 385, 'text': 'Cubic Odyssey', 'notable': false},
    {'id': 386, 'text': 'Preserve', 'notable': false},
    {'id': 387, 'text': 'Trizon', 'notable': false},
    {'id': 388, 'text': 'DOOM: The Dark Ages', 'notable': false},
    {'id': 389, 'text': 'Nubs! Arena', 'notable': false},
    {'id': 390, 'text': 'Yasha: Legends of the Demon Blade', 'notable': false},
    {'id': 391, 'text': 'Capcom Fighting Collection 2', 'notable': false},
    {'id': 392, 'text': 'Crafty Survivors', 'notable': false},
    {'id': 393, 'text': 'Bioprototype', 'notable': false},
    {'id': 394, 'text': 'ddddNitro Express', 'notable': false},
    {'id': 395, 'text': 'Kathy Rain 2: Soothsayer', 'notable': false},
    {'id': 396, 'text': 'Desktop Survivors 98', 'notable': false},
    {'id': 397, 'text': 'Villages & Dungeons', 'notable': false},
    {'id': 398, 'text': 'RoadCraft', 'notable': false},
    {'id': 399, 'text': 'Monster Train 2', 'notable': false},
    {'id': 400, 'text': 'FANTASY LIFE i: The Girl Who Steals Time', 'notable': false},
    {'id': 401, 'text': 'Cauldron', 'notable': false},
    {'id': 402, 'text': 'JDM: Japanese Drift Master', 'notable': false},
    {'id': 403, 'text': 'Game of Thrones: Kingsroad', 'notable': false},
    {'id': 404, 'text': 'Riot Control Simulator: Rookie Day', 'notable': false},
    {'id': 405, 'text': 'Duck Detective: The Ghost of Glamping', 'notable': false},
    {'id': 406, 'text': 'Out of Sight', 'notable': false},
    {'id': 407, 'text': 'Bugtopia', 'notable': false},
    {'id': 408, 'text': 'Warhammer 40,000: Boltgun - Words of Vengeance', 'notable': false},
    {'id': 409, 'text': 'Bloodshed', 'notable': false},
    {'id': 410, 'text': 'Worshippers of Cthulhu', 'notable': false},
    {'id': 411, 'text': 'Warhammer 40,000: Speed Freeks', 'notable': false},
    {'id': 412, 'text': 'Survive the Fall', 'notable': false},
    {'id': 413, 'text': 'Catgirl', 'notable': false},
    {'id': 414, 'text': 'The Ranch of Rivershine', 'notable': false},
    {'id': 415, 'text': 'Auto Rogue', 'notable': false},
    {'id': 416, 'text': 'Tainted Grail: The Fall of Avalon', 'notable': false},
    {'id': 417, 'text': 'Onimusha 2: Samurai\'s Destiny', 'notable': false},
    {'id': 418, 'text': 'Coin Push RPG', 'notable': false},
    {'id': 419, 'text': 'Snacko', 'notable': false},
    {'id': 420, 'text': 'ContractVille', 'notable': false},
    {'id': 421, 'text': 'Section 13', 'notable': false},
    {'id': 422, 'text': 'Oddsparks: An Automation Adventure', 'notable': false},
    {'id': 423, 'text': 'Kabuto Park', 'notable': false},
    {'id': 424, 'text': 'Pipistrello and the Cursed Yoyo', 'notable': false},
    {'id': 425, 'text': 'Trash Goblin', 'notable': false},
    {'id': 426, 'text': 'Project Warlock II', 'notable': false},
    {'id': 427, 'text': 'Squad 22: ZOV', 'notable': false},
    {'id': 428, 'text': 'Guilty as Sock!', 'notable': false},
    {'id': 429, 'text': 'Car Dealer Simulator', 'notable': false},
    {'id': 430, 'text': 'The Break-In', 'notable': false},
    {'id': 431, 'text': 'Nice Day for Fishing', 'notable': false},
    {'id': 432, 'text': 'Wrap House Simulator🌯', 'notable': false},
    {'id': 433, 'text': 'ELDEN RING NIGHTREIGN', 'notable': false},
    {'id': 434, 'text': 'Farm Together 2', 'notable': false},
    {'id': 435, 'text': 'F1® 25', 'notable': false},
    {'id': 436, 'text': 'Paranormal Cleanup', 'notable': false},
    {'id': 437, 'text': '', 'notable': false},
    {'id': 438, 'text': 'JUNE', 'notable': false},
    {'id': 439, 'text': '-----------------', 'notable': false},
    {'id': 440, 'text': 'The New Flesh', 'notable': false},
    {'id': 441, 'text': 'Void War', 'notable': false},
    {'id': 442, 'text': 'Cyber Knights: Flashpoint', 'notable': false},
    {'id': 443, 'text': 'POPUCOM', 'notable': false},
    {'id': 444, 'text': 'Galactic Glitch', 'notable': false},
    {'id': 445, 'text': 'DELTARUNE', 'notable': false},
    {'id': 446, 'text': 'Rune Factory: Guardians of Azuma', 'notable': false},
    {'id': 447, 'text': 'Donkey Kong: Banaza', 'notable': false},
    {'id': 448, 'text': 'Mario Kart World', 'notable': false},
    {'id': 449, 'text': 'Nintendo Switch 2 Welcome Tour', 'notable': false},
    {'id': 450, 'text': 'Cellveillance', 'notable': false},
    {'id': 451, 'text': 'Drift Legends 2', 'notable': false},
    {'id': 452, 'text': 'Pro Cycling Manager 25', 'notable': false},
    {'id': 453, 'text': 'Dragon Is Dead', 'notable': false},
    {'id': 454, 'text': 'Squeakross: Home Squeak Home', 'notable': false},
    {'id': 455, 'text': 'Camper Van: Make it Home', 'notable': false},
    {'id': 456, 'text': 'Dune: Awakening', 'notable': false},
    {'id': 457, 'text': 'MindsEye', 'notable': false},
    {'id': 458, 'text': 'Wizard of Legend 2', 'notable': false},
    {'id': 459, 'text': 'Backpack Battles', 'notable': false},
    {'id': 460, 'text': 'The Alters', 'notable': false},
    {'id': 461, 'text': 'Path of the Abyss', 'notable': false},
    {'id': 462, 'text': 'Big Winner', 'notable': false},
    {'id': 463, 'text': 'Shadowverse: Worlds Beyond', 'notable': false},
    {'id': 464, 'text': 'PEAK', 'notable': false},
    {'id': 465, 'text': 'Cast n Chill', 'notable': false},
    {'id': 466, 'text': 'Fallen Arena', 'notable': false},
    {'id': 467, 'text': 'Date Everything!', 'notable': false},
    {'id': 468, 'text': 'Lost in Random: The Eternal Die', 'notable': false},
    {'id': 469, 'text': 'Crime Simulator', 'notable': false},
    {'id': 470, 'text': 'Three Kingdoms Mushouden', 'notable': false},
    {'id': 471, 'text': 'FBC: Firebreak', 'notable': false},
    {'id': 472, 'text': 'Loot of Baal', 'notable': false},
    {'id': 473, 'text': 'Kindergarten 3', 'notable': false},
    {'id': 474, 'text': 'Card Shop Simulator Multiplayer', 'notable': false},
    {'id': 475, 'text': 'Tower Wizard', 'notable': false},
    {'id': 476, 'text': 'RAIDOU Remastered: The Mystery of the Soulless Army', 'notable': false},
    {'id': 477, 'text': 'Yaoling: Mythical Journey', 'notable': false},
    {'id': 478, 'text': 'REMATCH', 'notable': false},
    {'id': 479, 'text': 'Broken Arrow', 'notable': false},
    {'id': 480, 'text': 'Parcel Simulator', 'notable': false},
    {'id': 481, 'text': 'Suit for Hire', 'notable': false},
    {'id': 482, 'text': 'Ark Nova', 'notable': false},
    {'id': 483, 'text': 'Tobacco Shop Simulator', 'notable': false},
    {'id': 484, 'text': 'Tiny Aquarium: Social Fishkeeping', 'notable': false},
    {'id': 485, 'text': 'Ship, Inc.', 'notable': false},
    {'id': 486, 'text': 'Umamusume: Pretty Derby', 'notable': false},
    {'id': 487, 'text': 'Click and Conquer', 'notable': false},
    {'id': 488, 'text': 'Storage Dealer Simulator', 'notable': false},
    {'id': 489, 'text': 'Far Fishing', 'notable': false},
    {'id': 490, 'text': 'Death Stranding 2: On the Beach', 'notable': false},
    {'id': 491, 'text': 'System Shock 2: 25th Anniversary Remaster', 'notable': false},
    {'id': 492, 'text': 'Persona5: The Phantom X', 'notable': false},
    {'id': 493, 'text': 'Summer Pockets REFLECTION BLUE', 'notable': false},
    {'id': 494, 'text': '', 'notable': false},
    {'id': 495, 'text': 'JULY', 'notable': false},
    {'id': 496, 'text': '------------------', 'notable': false},
    {'id': 497, 'text': 'Aura Kingdom - Impact', 'notable': false},
    {'id': 498, 'text': 'Mecha BREAK', 'notable': false},
    {'id': 499, 'text': 'Blue Archive', 'notable': false},
    {'id': 500, 'text': 'vivid/stasis', 'notable': false},
    {'id': 501, 'text': 'ISLANDERS: New Shores', 'notable': false},
    {'id': 502, 'text': 'DOGWALK', 'notable': false},
    {'id': 503, 'text': 'Last Report', 'notable': false},
    {'id': 504, 'text': 'Crisis in the Kremlin: The Cold War', 'notable': false},
    {'id': 505, 'text': 'Dread Flats', 'notable': false},
    {'id': 506, 'text': 'Climb The Backrooms', 'notable': false},
    {'id': 507, 'text': 'Tony Hawk\'s Pro Skater 3 + 4', 'notable': false},
    {'id': 508, 'text': 'Astro Prospector', 'notable': false},
    {'id': 509, 'text': 'Kaizen: A Factory Story', 'notable': false},
    {'id': 510, 'text': 'C.A.S.T. (CHERNOZEM ANOMALY STRIKE TEAM)', 'notable': false},
    {'id': 511, 'text': 'Eriksholm: The Stolen Dream', 'notable': false},
    {'id': 512, 'text': 'Stronghold Crusader: Definitive Edition', 'notable': false},
    {'id': 513, 'text': 'The Three Kingdoms: The Tales of Jian An', 'notable': false},
    {'id': 514, 'text': 'That One Otter Game', 'notable': false},
    {'id': 515, 'text': 'Ratten Reich', 'notable': false},
    {'id': 516, 'text': 'Dungeons & Dragons Neverwinter Nights 2: Enhanced Edition', 'notable': false},
    {'id': 517, 'text': 'Demonic Mahjong', 'notable': false},
    {'id': 518, 'text': 'Madoka Magica Magia Exedra', 'notable': false},
    {'id': 519, 'text': 'The Drifter', 'notable': false},
    {'id': 520, 'text': 'Fretless - The Wrath of Riffson', 'notable': false},
    {'id': 521, 'text': 'The Wandering Village', 'notable': false},
    {'id': 522, 'text': 'The Necromancer\'s Tale', 'notable': false},
    {'id': 523, 'text': 'Fill Up The Hole', 'notable': false},
    {'id': 524, 'text': 'RoboCop: Rogue City - Unfinished Business', 'notable': false},
    {'id': 525, 'text': 'Drill Core', 'notable': false},
    {'id': 526, 'text': 'LostMagic', 'notable': false},
    {'id': 527, 'text': 'Off The Grid', 'notable': false},
    {'id': 528, 'text': 'Back to the Dawn', 'notable': false},
    {'id': 529, 'text': 'Who\'s at the door?', 'notable': false},
    {'id': 530, 'text': 'The Complex: Expedition', 'notable': false},
    {'id': 531, 'text': 'Return from Core', 'notable': false},
    {'id': 532, 'text': 'Little Fighter 2 Remastered', 'notable': false},
    {'id': 533, 'text': 'The King is Watching', 'notable': false},
    {'id': 534, 'text': 'Luto', 'notable': false},
    {'id': 535, 'text': 'WolfQuest: Anniversary Edition', 'notable': false},
    {'id': 536, 'text': 'Monument Valley 3', 'notable': false},
    {'id': 537, 'text': 'Hell Clock', 'notable': false},
    {'id': 538, 'text': 'Wildgate', 'notable': false},
    {'id': 539, 'text': 'and Roger', 'notable': false},
    {'id': 540, 'text': 'Wheel World', 'notable': false},
    {'id': 541, 'text': 'Animal Shelter 2', 'notable': false},
    {'id': 542, 'text': 's.p.l.i.t', 'notable': false},
    {'id': 543, 'text': 'Ghost Watchers', 'notable': false},
    {'id': 544, 'text': 'The Great Villainess: Strategy of Lily', 'notable': false},
    {'id': 545, 'text': 'Let Them Trade', 'notable': false},
    {'id': 546, 'text': 'WUCHANG: Fallen Feathers', 'notable': false},
    {'id': 547, 'text': 'Killing Floor 3', 'notable': false},
    {'id': 548, 'text': 'Paddle Paddle Paddle', 'notable': false},
    {'id': 549, 'text': 'Prison Escape Simulator: Dig Out', 'notable': false},
    {'id': 550, 'text': 'No Sleep For Kaname Date - From AI: THE SOMNIUM FILES', 'notable': false},
    {'id': 551, 'text': 'One-Eyed Likho', 'notable': false},
    {'id': 552, 'text': 'Tales of the Shire: A The Lord of The Rings Game', 'notable': false},
    {'id': 553, 'text': 'Achilles: Survivor', 'notable': false},
    {'id': 554, 'text': 'Terminull Brigade', 'notable': false},
    {'id': 555, 'text': 'Keep on Mining!', 'notable': false},
    {'id': 556, 'text': 'NINJA GAIDEN: Ragebound', 'notable': false},
    {'id': 557, 'text': 'Wires And Whiskers', 'notable': false},
    {'id': 558, 'text': 'Dead Take', 'notable': false},
    {'id': 559, 'text': 'Lakeside Bar', 'notable': false},
    {'id': 560, 'text': 'Mecharashi', 'notable': false},
    {'id': 561, 'text': '', 'notable': false},
    {'id': 562, 'text': 'AUGUST', 'notable': false},
    {'id': 563, 'text': '----------------------', 'notable': false},
    {'id': 564, 'text': 'Driftwood', 'notable': false},
    {'id': 565, 'text': 'Gatekeeper', 'notable': false},
    {'id': 566, 'text': 'Fuel Harvest Together', 'notable': false},
    {'id': 567, 'text': 'Catto\'s Post Office', 'notable': false},
    {'id': 568, 'text': 'Liftoff®: Micro Drones', 'notable': false},
    {'id': 569, 'text': 'Sensei! I Like You So Much!', 'notable': false},
    {'id': 570, 'text': 'A Few Quick Matches', 'notable': false},
    {'id': 571, 'text': 'Demon Slayer -Kimetsu no Yaiba- The Hinokami Chronicles 2', 'notable': false},
    {'id': 572, 'text': 'Stormgate', 'notable': false},
    {'id': 573, 'text': 'Fate/hollow ataraxia REMASTERED', 'notable': false},
    {'id': 574, 'text': 'Static Dread: The Lighthouse', 'notable': false},
    {'id': 575, 'text': 'Öoo', 'notable': false},
    {'id': 576, 'text': 'Is This Seat Taken?', 'notable': false},
    {'id': 577, 'text': 'Tiny Bookshop', 'notable': false},
    {'id': 578, 'text': 'Heretic + Hexen', 'notable': false},
    {'id': 579, 'text': 'Gemporium: A Cute Mining Sim', 'notable': false},
    {'id': 580, 'text': 'MakeRoom', 'notable': false},
    {'id': 581, 'text': 'The RPG', 'notable': false},
    {'id': 582, 'text': 'GUNTOUCHABLES', 'notable': false},
    {'id': 583, 'text': 'Artis Impact', 'notable': false},
    {'id': 584, 'text': 'Mafia: The Old Country', 'notable': false},
    {'id': 585, 'text': 'Fischer\'s Fishing Journey', 'notable': false},
    {'id': 586, 'text': 'Deadzone: Rogue', 'notable': false},
    {'id': 587, 'text': 'Abyssus', 'notable': false},
    {'id': 588, 'text': 'Echoes of the End: Enhanced Edition', 'notable': false},
    {'id': 589, 'text': 'The Bazaar', 'notable': false},
    {'id': 590, 'text': 'Drag x Drive', 'notable': false},
    {'id': 591, 'text': 'Midnight Murder Club', 'notable': false},
    {'id': 592, 'text': 'Dice Gambit', 'notable': false},
    {'id': 593, 'text': 'BACKROOMS: APPREHENSION', 'notable': false},
    {'id': 594, 'text': 'EA SPORTS Madden NFL 26', 'notable': false},
    {'id': 595, 'text': 'OFF', 'notable': false},
    {'id': 596, 'text': 'Whispers from the Star', 'notable': false},
    {'id': 597, 'text': 'Bendy: Lone Wolf', 'notable': false},
    {'id': 598, 'text': 'The Dark Queen of Mortholme', 'notable': false},
    {'id': 599, 'text': 'Touhou Kinjoukyou ～ Fossilized Wonders.', 'notable': false},
    {'id': 600, 'text': 'Sword of the Sea', 'notable': false},
    {'id': 601, 'text': 'BAPBAP', 'notable': false},
    {'id': 602, 'text': 'The Rogue Prince of Persia', 'notable': false},
    {'id': 603, 'text': 'Herdling', 'notable': false},
    {'id': 604, 'text': 'Discounty', 'notable': false},
    {'id': 605, 'text': 'Knightica', 'notable': false},
    {'id': 606, 'text': 'Ways of Alchemy', 'notable': false},
    {'id': 607, 'text': 'Gears of War: Reloaded', 'notable': false},
    {'id': 608, 'text': 'Whisper of the House', 'notable': false},
    {'id': 609, 'text': 'STORY OF SEASONS: Grand Bazaar', 'notable': false},
    {'id': 610, 'text': 'SUPER ROBOT WARS Y', 'notable': false},
    {'id': 611, 'text': 'Garten of Banban 8: Anti Devil', 'notable': false},
    {'id': 612, 'text': 'METAL GEAR SOLID Δ: SNAKE EATER', 'notable': false},
    {'id': 613, 'text': 'Mortal Sin', 'notable': false},
    {'id': 614, 'text': 'Plan B: Terraform', 'notable': false},
    {'id': 615, 'text': 'SHINOBI: Art of Vengeance', 'notable': false},
    {'id': 616, 'text': 'Dungeon Warfare 3', 'notable': false},
    {'id': 617, 'text': 'Lost Soul Aside', 'notable': false},
    {'id': 618, 'text': 'Sinister Night 2', 'notable': false},
    {'id': 619, 'text': 'Farming & Supermarket Simulator', 'notable': false},
    {'id': 620, 'text': '', 'notable': false},
    {'id': 621, 'text': 'SEPTEMBER', 'notable': false},
    {'id': 622, 'text': '---------------------', 'notable': false},
    {'id': 623, 'text': 'Overlooting', 'notable': false},
    {'id': 624, 'text': 'METAL EDEN', 'notable': false},
    {'id': 625, 'text': 'World War Legion', 'notable': false},
    {'id': 626, 'text': 'Kemono Teatime', 'notable': false},
    {'id': 627, 'text': 'Hell is Us', 'notable': false},
    {'id': 628, 'text': 'Hollow Knight: Silksong', 'notable': false},
    {'id': 629, 'text': 'EVERYBODY\'S GOLF HOT SHOTS', 'notable': false},
    {'id': 630, 'text': 'Cronos: The New Dawn', 'notable': false},
    {'id': 631, 'text': 'Daemon X Machina: Titanic Scion', 'notable': false},
    {'id': 632, 'text': 'NBA 2K26', 'notable': false},
    {'id': 633, 'text': 'Star Fire: Eternal Cycle', 'notable': false},
    {'id': 634, 'text': 'Trainatic', 'notable': false},
    {'id': 635, 'text': 'Supercar Collection Simulator', 'notable': false},
    {'id': 636, 'text': 'Firefighting Simulator: Ignite', 'notable': false},
    {'id': 637, 'text': 'DRAGON BALL GEKISHIN SQUADRA', 'notable': false},
    {'id': 638, 'text': 'Shape of Dreams', 'notable': false},
    {'id': 639, 'text': 'Dungeons of Eternity', 'notable': false},
    {'id': 640, 'text': 'Keep Digging', 'notable': false},
    {'id': 641, 'text': 'Borderlands 4', 'notable': false},
    {'id': 642, 'text': 'Chrono Gear: Warden of Time', 'notable': false},
    {'id': 643, 'text': 'Coal LLC', 'notable': false},
    {'id': 644, 'text': 'Misty Judgment', 'notable': false},
    {'id': 645, 'text': 'RAM: Random Access Mayhem', 'notable': false},
    {'id': 646, 'text': 'No, I\'m not a Human', 'notable': false},
    {'id': 647, 'text': 'Little Witch in the Woods', 'notable': false},
    {'id': 648, 'text': 'M.A.S.S. Builder', 'notable': false},
    {'id': 649, 'text': 'LEGO® Voyagers', 'notable': false},
    {'id': 650, 'text': 'Greedland', 'notable': false},
    {'id': 651, 'text': 'Monster Care Simulator', 'notable': false},
    {'id': 652, 'text': 'Rana Card', 'notable': false},
    {'id': 653, 'text': 'Roman Triumph: Survival City Builder', 'notable': false},
    {'id': 654, 'text': 'Arena Breakout: Infinite', 'notable': false},
    {'id': 655, 'text': 'BRAZILIAN DRUG DEALER 3: I OPENED A PORTAL TO HELL IN THE FAVELA TRYING TO REVIVE MIT AIA I NEED TO CLOSE IT', 'notable': false},
    {'id': 656, 'text': 'Strange Antiquities', 'notable': false},
    {'id': 657, 'text': 'Ale Abbey - Monastery Brewery Tycoon', 'notable': false},
    {'id': 658, 'text': 'ShapeHero Factory', 'notable': false},
    {'id': 659, 'text': 'Lost Skies', 'notable': false},
    {'id': 660, 'text': 'Deadeye Deepfake Simulacrum', 'notable': false},
    {'id': 661, 'text': 'Megabonk', 'notable': false},
    {'id': 662, 'text': 'Easy Delivery Co.', 'notable': false},
    {'id': 663, 'text': 'Dying Light: The Beast', 'notable': false},
    {'id': 664, 'text': 'A Gentlemen\'s Dispute', 'notable': false},
    {'id': 665, 'text': 'Eclipsium', 'notable': false},
    {'id': 666, 'text': 'Trails in the Sky 1st Chapter', 'notable': false},
    {'id': 667, 'text': 'The Spike Cross', 'notable': false},
    {'id': 668, 'text': 'Warborne Above Ashes', 'notable': false},
    {'id': 669, 'text': 'Cozy Island', 'notable': false},
    {'id': 670, 'text': 'Slime Rancher 2', 'notable': false},
    {'id': 671, 'text': 'Baby Steps', 'notable': false},
    {'id': 672, 'text': 'SWORN', 'notable': false},
    {'id': 673, 'text': 'Deconstruction Simulator', 'notable': false},
    {'id': 674, 'text': 'TouHou Makuka Sai ~ Fantastic Danmaku Festival Part III', 'notable': false},
    {'id': 675, 'text': 'Blade & Soul Heroes', 'notable': false},
    {'id': 676, 'text': 'Hades II', 'notable': false},
    {'id': 677, 'text': 'Sonic Racing: CrossWorlds', 'notable': false},
    {'id': 678, 'text': 'Mars First Logistics', 'notable': false},
    {'id': 679, 'text': 'Unfair Flips', 'notable': false},
    {'id': 680, 'text': 'PAC-MAN WORLD 2 Re-PAC', 'notable': false},
    {'id': 681, 'text': 'SILENT HILL f', 'notable': false},
    {'id': 682, 'text': 'EA SPORTS FC 26', 'notable': false},
    {'id': 683, 'text': 'CloverPit', 'notable': false},
    {'id': 684, 'text': 'Atelier Resleriana: The Red Alchemist & the White Guardian', 'notable': false},
    {'id': 685, 'text': 'IDLE BOSS RUSH', 'notable': false},
    {'id': 686, 'text': 'FINAL FANTASY TACTICS - The Ivalice Chronicles', 'notable': false},
    {'id': 687, 'text': 'LEGO® Party!', 'notable': false},
    {'id': 688, 'text': '', 'notable': false},
    {'id': 689, 'text': 'OCTOBER', 'notable': false},
    {'id': 690, 'text': '-----------------', 'notable': false},
    {'id': 691, 'text': 'Train Sim World® 6', 'notable': false},
    {'id': 692, 'text': 'KAIJU NO. 8 THE GAME', 'notable': false},
    {'id': 693, 'text': 'Digimon Story Time Stranger', 'notable': false},
    {'id': 694, 'text': 'Ghost of Yotei', 'notable': false},
    {'id': 695, 'text': 'Upload Labs', 'notable': false},
    {'id': 696, 'text': 'CARIMARA: Beneath the forlorn limbs', 'notable': false},
    {'id': 697, 'text': 'Little Rocket Lab', 'notable': false},
    {'id': 698, 'text': 'Absolum', 'notable': false},
    {'id': 699, 'text': 'Yooka-Replaylee', 'notable': false},
    {'id': 700, 'text': 'Lost Eidolons: Veil of the Witch', 'notable': false},
    {'id': 701, 'text': 'Bye Sweet Carole', 'notable': false},
    {'id': 702, 'text': 'Blue Protocol: Star Resonance', 'notable': false},
    {'id': 703, 'text': 'Little Nightmares III', 'notable': false},
    {'id': 704, 'text': 'The Farmer Was Replaced', 'notable': false},
    {'id': 705, 'text': 'Project Unknown', 'notable': false},
    {'id': 706, 'text': 'Battlefield 6', 'notable': false},
    {'id': 707, 'text': 'BALL x PIT', 'notable': false},
    {'id': 708, 'text': 'Habbo Hotel: Origins', 'notable': false},
    {'id': 709, 'text': 'Escape From Duckov', 'notable': false},
    {'id': 710, 'text': 'Pokemon Legends: Z-A', 'notable': false},
    {'id': 711, 'text': 'Touhou Dystopian', 'notable': false},
    {'id': 712, 'text': 'NINJA GAIDEN 4', 'notable': false},
    {'id': 713, 'text': 'Lessaria: Fantasy Kingdom Sim', 'notable': false},
    {'id': 714, 'text': 'Jurassic World Evolution 3', 'notable': false},
    {'id': 715, 'text': 'RV There Yet?', 'notable': false},
    {'id': 716, 'text': 'Painkiller', 'notable': false},
    {'id': 717, 'text': 'Vampire: The Masquerade® - Bloodlines 2', 'notable': false},
    {'id': 718, 'text': 'Dispatch', 'notable': false},
    {'id': 719, 'text': 'Once Upon A KATAMARI', 'notable': false},
    {'id': 720, 'text': 'Farthest Frontier', 'notable': false},
    {'id': 721, 'text': 'MISERY', 'notable': false},
    {'id': 722, 'text': 'Dark Hours', 'notable': false},
    {'id': 723, 'text': 'Tormented Souls 2', 'notable': false},
    {'id': 724, 'text': 'PowerWash Simulator 2', 'notable': false},
    {'id': 725, 'text': 'J-Jump Arena', 'notable': false},
    {'id': 726, 'text': 'Crown and Adventure', 'notable': false},
    {'id': 727, 'text': 'Slots & Daggers', 'notable': false},
    {'id': 728, 'text': 'Escape Simulator 2', 'notable': false},
    {'id': 729, 'text': 'Master of Command', 'notable': false},
    {'id': 730, 'text': 'The Outer Worlds 2', 'notable': false},
    {'id': 731, 'text': 'Dungeon Stalkers', 'notable': false},
    {'id': 732, 'text': 'ARC Raiders', 'notable': false},
    {'id': 733, 'text': 'The Front', 'notable': false}
]